package com.onsgold.admin.ui.theme

import androidx.compose.ui.graphics.Color

val GoldPrimary = Color(0xFF1A56DB)
val GoldOnPrimary = Color(0xFFFFFFFF)
val GoldPrimaryContainer = Color(0xFFE8F0FF)
val GoldOnPrimaryContainer = Color(0xFF0F2E72)
val GoldSecondary = Color(0xFF3B82F6)
val GoldOnSecondary = Color(0xFFFFFFFF)
val GoldSecondaryContainer = Color(0xFFDCEBFF)
val GoldOnSecondaryContainer = Color(0xFF12356F)
val GoldBackground = Color(0xFFFFFFFF)
val GoldOnBackground = Color(0xFF0F172A)
val GoldSurface = Color(0xFFFFFFFF)
val GoldOnSurface = Color(0xFF111827)
val GoldSurfaceVariant = Color(0xFFEAF4FF)
val GoldOnSurfaceVariant = Color(0xFF31527A)
val GoldError = Color(0xFFB3261E)
val GoldOnError = Color(0xFFFFFFFF)

val GoldPrimaryDark = Color(0xFF1A56DB)
val GoldOnPrimaryDark = Color(0xFFFFFFFF)
val GoldSecondaryDark = Color(0xFF3B82F6)
val GoldOnSecondaryDark = Color(0xFFFFFFFF)
val GoldBackgroundDark = Color(0xFFFFFFFF)
val GoldOnBackgroundDark = Color(0xFF0F172A)
val GoldSurfaceDark = Color(0xFFFFFFFF)
val GoldOnSurfaceDark = Color(0xFF111827)
val GoldSurfaceVariantDark = Color(0xFFEAF4FF)
val GoldOnSurfaceVariantDark = Color(0xFF31527A)
val GoldErrorDark = Color(0xFFB3261E)
val GoldOnErrorDark = Color(0xFFFFFFFF)
